name: Rebuild
on:
  workflow_dispatch:
jobs:
  rebuild:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rebuild
        run: |
         npm install
         npm run prepublish
      - name: Archive
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          path: output.zip
