name: Rebuild
on:
  workflow_dispatch:
  push:
jobs:
  rebuild:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rebuild
        run: |
         npm install
         npm run prepublish
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: PenguinMod/PenguinMod-Gui
